import type {
  Business,
  ChainRow,
  Distribution,
  EvidenceItem,
  InvestmentRow,
  KycCase,
} from "./types";

export const reviewer = {
  email: "reviewer@barakahshares.test",
  password: "Demo1234",
  name: "Fatuma Noor",
  role: "Compliance reviewer",
};

export const businesses: Business[] = [
  {
    id: "al-yusra",
    name: "Al-Yusra Restaurant",
    location: "Eastleigh, Nairobi",
    owner: "Ahmed",
    category: "Dining",
    summary:
      "Operating halal restaurant offering 40% equity for a dining-room refit. Investors share profit, not interest.",
    monthlyProfitKes: 412000,
    targetKes: 2000000,
    sharePriceKes: 10000,
    totalShares: 200,
    filledShares: 132,
    equityOffered: 40,
    investorPool: 40,
    status: "funding",
    shariah: "verified",
    audit: "verified",
    halal: "verified",
    cma: "verified",
  },
  {
    id: "amani-abaya",
    name: "Amani Abaya Shop",
    location: "South C, Nairobi",
    owner: "Fatuma Noor",
    category: "Retail",
    summary: "Modest-wear retailer funding seasonal inventory. Equity, not a stock loan.",
    monthlyProfitKes: 150000,
    targetKes: 600000,
    sharePriceKes: 10000,
    totalShares: 60,
    filledShares: 36,
    equityOffered: 30,
    investorPool: 40,
    status: "funding",
    shariah: "verified",
    audit: "verified",
    halal: "verified",
    cma: "verified",
  },
  {
    id: "ruai-poultry",
    name: "Ruai Halal Poultry Farm",
    location: "Ruai, Nairobi",
    owner: "Ibrahim Otieno",
    category: "Agriculture",
    summary: "Flock expansion from 2,000 toward 5,000 birds. Profit follows completed cycles.",
    monthlyProfitKes: 180000,
    targetKes: 1250000,
    sharePriceKes: 10000,
    totalShares: 125,
    filledShares: 50,
    equityOffered: 35,
    investorPool: 40,
    status: "funding",
    shariah: "verified",
    audit: "pending",
    halal: "verified",
    cma: "pending",
  },
  {
    id: "halal-logistics",
    name: "Halal Logistics",
    location: "Eastleigh → Garissa",
    owner: "Yusuf Abdi",
    category: "Logistics",
    summary: "Corridor haulage. The raise stays closed until the audit pack is complete.",
    monthlyProfitKes: 96000,
    targetKes: 900000,
    sharePriceKes: 10000,
    totalShares: 90,
    filledShares: 0,
    equityOffered: 25,
    investorPool: 40,
    status: "funding_soon",
    shariah: "pending",
    audit: "pending",
    halal: "verified",
    cma: "failed",
  },
];

export const kycCases: KycCase[] = [
  {
    id: "investor-abdullahi",
    name: "Abdullahi Hassan",
    phone: "+254 700 000 000",
    role: "Youth Investor",
    status: "verified",
    submittedAt: "12 Sep 2026",
    note: "Demo record. No national ID is stored in this console.",
  },
  {
    id: "investor-amina",
    name: "Amina Yusuf",
    phone: "+254 711 222 333",
    role: "Youth Investor",
    status: "pending",
    submittedAt: "04 Oct 2026",
    note: "Waiting for a reviewer decision. Smile ID is not called from this demo.",
  },
  {
    id: "investor-hassan",
    name: "Hassan Ali",
    phone: "+254 722 444 555",
    role: "Business Owner",
    status: "failed",
    submittedAt: "28 Sep 2026",
    note: "Marked failed in the demo queue. The ID image is not shown.",
  },
];

export const investments: InvestmentRow[] = [
  {
    id: "inv-alyusra",
    investor: "Abdullahi Hassan",
    businessId: "al-yusra",
    business: "Al-Yusra Restaurant",
    amountKes: 10000,
    shares: 1,
    ownership: "0.5%",
    certificate: "BARAKAH-SHARE-0088",
    status: "Active",
  },
  {
    id: "inv-amani",
    investor: "Abdullahi Hassan",
    businessId: "amani-abaya",
    business: "Amani Abaya Shop",
    amountKes: 20000,
    shares: 2,
    ownership: "3.33%",
    certificate: "BARAKAH-SHARE-0114",
    status: "Active",
  },
  {
    id: "inv-ruai",
    investor: "Abdullahi Hassan",
    businessId: "ruai-poultry",
    business: "Ruai Halal Poultry Farm",
    amountKes: 20000,
    shares: 2,
    ownership: "1.6%",
    certificate: "BARAKAH-SHARE-0142",
    status: "Active",
  },
];

export const evidence: EvidenceItem[] = [
  {
    id: "rc-rent",
    businessId: "al-yusra",
    business: "Al-Yusra Restaurant",
    title: "Rent",
    category: "Premises",
    amountKes: 60000,
    date: "02 Jun 2026",
    sha256: "a3f1c9e21b0044aa9812cc771090ab12ef44556677889900aabbccddeeff0011",
    cid: "QmYusraRent8f3a21c9b71",
    verified: true,
  },
  {
    id: "rc-stock",
    businessId: "al-yusra",
    business: "Al-Yusra Restaurant",
    title: "Stock",
    category: "Inventory",
    amountKes: 80000,
    date: "08 Jun 2026",
    sha256: "b41d88aa0912cc3400ef12ab77889910aabbccdd11223344556677889900ab12",
    cid: "QmYusraStock4b91e20aa12",
    verified: true,
  },
  {
    id: "rc-licence",
    businessId: "al-yusra",
    business: "Al-Yusra Restaurant",
    title: "Licensing",
    category: "Licensing",
    amountKes: 10000,
    date: "14 Jun 2026",
    sha256: "c55e12ab90ff44120098aa7711bb22cc33dd44ee55ff66778899aabbccddeeff",
    cid: "QmYusraLicense77c31a90",
    verified: false,
  },
];

export const distributions: Distribution[] = [
  {
    id: "profit-alyusra",
    businessId: "al-yusra",
    business: "Al-Yusra Restaurant",
    period: "June 2026",
    grossKes: 500000,
    expensesKes: 100000,
    ownerPercent: 60,
    investorPercent: 40,
    sharesOwned: 1,
    totalShares: 200,
    status: "pending",
  },
  {
    id: "profit-amani",
    businessId: "amani-abaya",
    business: "Amani Abaya Shop",
    period: "June 2026",
    grossKes: 120000,
    expensesKes: 37500,
    ownerPercent: 60,
    investorPercent: 40,
    sharesOwned: 2,
    totalShares: 60,
    status: "disbursed",
  },
  {
    id: "profit-ruai",
    businessId: "ruai-poultry",
    business: "Ruai Halal Poultry Farm",
    period: "June 2026",
    grossKes: 320000,
    expensesKes: 70000,
    ownerPercent: 60,
    investorPercent: 40,
    sharesOwned: 2,
    totalShares: 125,
    status: "disbursed",
  },
];

export const chainRows: ChainRow[] = [
  {
    id: "tx-invest",
    business: "Al-Yusra Restaurant",
    title: "Investment",
    amountKes: 10000,
    tx: "0x7a3f91c0b21e4d88aa01c4e29b7d10aa88c31e02",
    date: "12 Sep 2026",
    status: "Demo record",
  },
  {
    id: "tx-div",
    business: "Al-Yusra Restaurant",
    title: "Dividend distribution",
    amountKes: 800,
    tx: "0x91ab44e21890cc7712ab3490dd18ac771092ab31",
    date: "30 Sep 2026",
    status: "Demo record",
  },
  {
    id: "tx-hash",
    business: "Al-Yusra Restaurant",
    title: "Receipt hash anchored",
    amountKes: null,
    tx: "0xabcd12ef445090aa7812cc3490ab12ef7781aa09",
    date: "30 Jun 2026",
    status: "Demo record",
  },
];

export function poolAmount(net: number, percent: number) {
  return Math.round((net * percent) / 100);
}

export function yourDistribution(item: Distribution) {
  const net = item.grossKes - item.expensesKes;
  const pool = poolAmount(net, item.investorPercent);
  if (item.totalShares <= 0) return 0;
  return Math.round((pool * item.sharesOwned) / item.totalShares);
}
